### ISSUE TITLE
Cannot extract from modded tank with Ender Bucket (Thermal Expansion).

### ISSUE THREAD

**Issue by btcraig** [maruohon/enderutilities#1]
I am using version 0.3.5.1 and am not able to extract or insert fluids using Thermal Expansion's tanks and the Ender Bucket (in either Output or Input mode). I tested with a few fluids to see if it was isolated to just one but no liquids were able to be used. Of the fluids I tested were water, lava, and several fluids from MFR, Tinker's Construct, and TE.

However other tanks function correctly using Thermal Expansion fluids.

For reference this was happening in the mod pack Sky Factory 2.

**Comment by maruohon** [comment]
This is "fixed" (or more precisely worked around) since commit 87ce3feb73e069c1d82c4238b23451c675502157 (will be in release v0.4.0).
