### ISSUE TITLE
Suggestion: Ender Utilities Discord Server?

### ISSUE THREAD

**Issue by D3Gamer** [maruohon/enderutilities#111]
I didn't know where to write this---So hopefully this is the correct place to write this...

Is there an ender utilities discord server? If there isn't there should be one.

**Comment by maruohon** [comment]
It's not dedicated to EnU alone, and in fact has almost no discussions related to EnU but rather usually related to some of my other mods, but I do have my own Discord server, here: https://discord.gg/2FgywHj.
