### ISSUE TITLE
Bag Rendering issue

### ISSUE THREAD

**Issue by Thiana** [maruohon/enderutilities#12]
There is a rendering issue with Ender Utilities inventories and other mods. 

Screenshot #1 (hotbar with a mix of items from Thaumcraft/Not Enough Wands)
![2016-03-19_11 14 57](https://cloud.githubusercontent.com/assets/405832/13899415/09fe1f30-edc4-11e5-9ae0-c4890042fc7d.png)

The items render correctly (as they do in a the vanilla or baubles inventory).

Screenshot #2 (When you open a EU bag, you get this)
![2016-03-19_11 15 01](https://cloud.githubusercontent.com/assets/405832/13899422/30464b72-edc4-11e5-862b-e92d2587569f.png)

Thanks :)

Versions:
MC 1.8.9
Forge 1765
EU 0.5.0
NEW 1.2.9
TC 5.2.4

**Comment by maruohon** [comment]
This is a known issue, and it has been fixed in my development version already. The fix will be in the next release, 0.5.1. Thanks for reporting though :)

**Comment by maruohon** [comment]
Fixed in version 0.5.1.
