### ISSUE TITLE
Planting with Hoe eats hoe

### ISSUE THREAD

**Issue by Thiana** [maruohon/enderutilities#15]
In 0.5.2 using the ender hoe  to plant wheat seeds has some unexpected results... It plants the 3x3 pattern but then deletes the hoe :)

Procedure:
- Create a hoe with capacitor/core/link crystal.
- Set to player drops
- Get some seeds
- Right click on dirt, farmland is created without issue
- Right click again, seeds are planted and hoe vanishes.

Versions:
MC 1.8.9
Forge 1765
EU 0.5.2
JEI 2.28.7.174

Thanks :)

**Comment by Thiana** [comment]
It eats some of my inventory when I replicate it with my modpack but with just EU alone only the hoe is vanishing.

**Comment by maruohon** [comment]
Another thing derped in the move to IItemHandler ;_;
Fixed for the next version (0.5.3).
