### ISSUE TITLE
Crash when placing Tool Workbench

### ISSUE THREAD

**Issue by krelios** [maruohon/enderutilities#16]
When placing a tool workbench the game crashes and from there will crash any time you try to open the same world again.

[http://paste.ee/p/mZuOI](http://paste.ee/p/mZuOI)

Applies to 0.5.0 for Forge 1.9 (1858)

**Comment by maruohon** [comment]
Huh. Does this always happen, also in a new world? I couldn't reproduce this in my dev environment so I can't really test the fix... But I noticed a couple of (possible) bugs and changed those. Could you test if this build fixes it: http://masa.dy.fi/tmp/enderutilities-1.9-0.5.1.jar

**Comment by krelios** [comment]
That version fixed the crash for me, thanks for such fast work!

**Comment by maruohon** [comment]
Well I also noticed that you had Optifine installed and downloaded it and tried it with Optifine and got the same crash. And so I was also able to verify for myself that the fix works :)
