### ISSUE TITLE
Feature Request: Simple Sort

### ISSUE THREAD

**Issue by Thiana** [maruohon/enderutilities#17]
Could you please consider adding a simple sorting button for the expanded inventories? The two inventory sorting mods I'm aware of do *not* play well with stacksizes > 64 so you get rather nasty effects when sorting the larger disks. 

It doesnt need to be anything complex, just the ability to compress stacks and place like items next to each other. 

Thank you.

**Comment by maruohon** [comment]
Sure, the only question then is the rule that I would use to sort the items. Would it be the item name (the server doesn't know about localized names though... so maybe the item's registry name?) or just something like place all ItemBlocks next to each other and regular items after them or something similar? And should it have row and column modes similar to what Inventory Tweaks does?

Which version are you playing on btw? Would you need this in 1.8.9 or is 1.9 enough? At least I won't add any new stuff to 1.7.10 anymore and I would rather only focus on the 1.9 version. Supporting multiple versions and porting stuff and testing stuff in each version takes a lot of time and effort...

**Comment by Thiana** [comment]
The important part is placing the same stacks next to each other because over time I end up with incomplete stacks and non-contiguous blocks. Sorting with the registry name would probably be easiest? Though I do like the idea of separating blocks and items.

The row/column would probably be overkill. Most people just seem to use row sorting even when column sorting is available from what I've seen in streams.

One thing that would be nice is to treat each section differently in the case of the bag since I'm not sure about others but I use the left section for tools, top for blocks and right for consumables. 

I'm playing on 1.9. I'm rather addicted to Algo's Chisel and Bits at this point so I wont be dropping back to earlier versions :)

Thanks :)

**Comment by Thiana** [comment]
Works perfectly :) Thank you.
