### ISSUE TITLE
Restock Hotbar Only

### ISSUE THREAD

**Issue by Thiana** [maruohon/enderutilities#20]
Could you please consider adding another mode to the handy bag restocker? Instead of restocking the *entire* inventory, have an option to only restore items in the hotbar and offhand? With the current full inventory mode the restocker often seems to get confused and I end up with an inventory full of a single item.

Thank you.
PS: for MC1.10.2

**Comment by maruohon** [comment]
Heh yep the "confusion" comes from if anything puts a new item in your inventory (and the bag isn't in auto-pickup mode) then it will instantly re-stock those new stacks.

I'll add this new mode for the next release (1.9.4 and up). Thanks for the suggestion :)

**Comment by Thiana** [comment]
Thanks :)
