### ISSUE TITLE
Crash with Handy Bag 1.10.2

### ISSUE THREAD

**Issue by IBeCrayZ** [maruohon/enderutilities#25]
http://pastebin.com/uX8qbAvB

Issue with Handy bag when placed in the inventory, on matching & restock mode. Added memory card (6) and it crashed. Replicated when created new world however bag was in hotbar. Seems to be a restock issue according to the log, not an expert though. Also seems be happening when in those modes and then trying to add a memory card. Cannot replicate with Handy bag (large). Also a serious crash due to the fact the world won't load and can't be accessed after the crash (due to it crashing when trying to load the world).

**Comment by maruohon** [comment]
Yep found the issue, I had missed it when I added the lockable sections to the Large bag, since I basically never use the smaller bag in my test worlds... Now I just need to sort the fix for the 1.10.2 version, as my current dev environment is still in 1.9.4...

**Comment by maruohon** [comment]
A new release (1.10.2-0.6.5-beta.2) has now been uploaded to CurseForge.
