### ISSUE TITLE
TeleportEntity : saving data trouble

### ISSUE THREAD

**Issue by ArtixAllMighty** [maruohon/enderutilities#27]
You linked me to your teleport utlity (now called teleport entity) a long time ago. i still use it, because it's really well done.

ive ran into an issue though. custom data isn't getting saved when transporting the playe to another dimension. the only method i use for that is the " public static EntityPlayer transferPlayerToDimension(EntityPlayerMP player, int dimDst, BlockPos pos) "

You'll probably want to pop in an nbttag there, writetonbt and call readfromnbt.

or something like that... I'm currently looking for a solution myself.

**Comment by maruohon** [comment]
I'm closing this as invalid as discussed on IRC. (The mods are responsible for cloning any capabilities on dimension change.)
