### ISSUE TITLE
Ender Bag AE2 Multiparts

### ISSUE THREAD

**Issue by LiamHammett** [maruohon/enderutilities#3]
It's impossible to bind the Ender Bag to a multipart inventory in an Applied Energistics 2 ME network, such as the access terminal, crafting terminal, pattern terminal, etc. that are placed on wires. I imagine this would need custom code specific to these multiparts to work around this, but it would be insanely useful to have remote access to an ME network with something other than the limited ME Wireless Access Terminal.

**Comment by maruohon** [comment]
It is currently only possible to bind the bag to blocks that implement IInventory, so more or less blocks that have some sort of an inventory. Those AE blocks don't have an inventory in themselves, but they access the network via their own code. Even if I allowed binding, then there would be the same issues/crashes as you reported in #2.

I might see if there is anything I can do to allow this kind of behaviour with some sort of generic code in some point in the future, but it is not a priority right now, there is so much other stuff I want to add that has been just sitting on my TODO list for months.. This is a tricky thing to implement without nasty hackery or specialized code for everything, which would be impossible to maintain.

**Comment by maruohon** [comment]
There still isn't even an AE2 for 1.8+. And what's more, recently in 1.10 an event was removed from Forge that I was using for the Ender Bag previously, so this is even less feasible that it was before, without large amounts of extra (hacky) code.
