### ISSUE TITLE
Which license is used? :)

### ISSUE THREAD

**Issue by magnusjjj** [maruohon/enderutilities#35]
You have both the GPL and LGPL licenses in the root project listed. Which is the mod licensed under? :)

**Comment by maruohon** [comment]
The mod licensed is under LGPL-3.0.

Both license files are included since LGPL is based on GPL. This is also stated here: https://www.gnu.org/licenses/gpl-howto.en.html

> You should also include a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs the license is usually in a file called COPYING.

> If you are releasing your program under the LGPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's important to include both licenses so users have all the materials they need to understand their rights.
