### ISSUE TITLE
wand of the lazy builder - can't seem to toggle phantom blocks (paste mode)

### ISSUE THREAD

**Issue by DoomSquirter** [maruohon/enderutilities#39]
Enderutils-0.6.7

Tooltip for wotlb states alt-shift-toggle is used to show phantom blocks (for example, I am in paste mode)

but when I do this, third line that says Replace:no - Entities: no, the Entities: no changes to yes instead

iirc from other version, this worked fine.  I'm pointing in different directions and I'm not seeing any phantom blocks no matter which direction I change it to.

**Comment by maruohon** [comment]
Yes, the template-based modes don't currently have ghost block previews, only the "simple build modes" do, where you normally get the white bounding box for each block.

Adding ghost block previews to the Paste mode is on my TODO list though, if I can manage it without too many issues. So I'm hoping it would be included in version 0.7.0, but I can't say for sure if it will end up happening (nor is it guaranteed to happen at all, but I'm hoping to add it...).

**Comment by DoomSquirter** [comment]
oh that was very quick response!  lol  So, are you saying that ghost mode has never worked in paste mode?  I'd trust you 10 times over my fading memory if I had thought that worked before lol

**Comment by maruohon** [comment]
Yep, it has never existed in the Paste mode. I'd like you to find proof that it did, and I can then conclude that the reality is not real and give up on everything :D

**Comment by DoomSquirter** [comment]
noooooo reality isn't real!  :)  thanks so much for quick reply.  trying to get a friend into trying the wand since he's a huge chisel n bits fan and I mentioned you now have chisel n bits compat for templates, etc which is pretty neat.

**Comment by maruohon** [comment]
Do note though that the "C&B cross-world" compatibility is **only** meant for transferring the templates into a different world (with different block ID mappings). Normally, within the same world, you should leave it **off** for better performance and smaller template file size (like that really matters... but anyway). It simply isn't needed within the same world, it just works as-is.

I'm also hoping to add more C&B compatibility stuff in 0.7.0 though, at least allowing pasting C&B blocks in survival mode too (since they need to copy TileEntity data, which normally is not allowed in survival mode due to easy item duping).

I'd also like to allow for auto-crafting blocks from bits etc, but that is not guaranteed to happen, just something on my massive TODO list... :P

**Comment by DoomSquirter** [comment]
so I'm trying all directions and I had already saved a template and can't seem to paste that template in a new direction.  I hold down rclick and it doesn't do anything when I release.  I have all the blocks in my inventory.  I've used this before a month or so ago, so I swear I'm doing this right.

in copy mode, I selected first corner shift left click, then went to next corner and shift right clicked, then hit copy and gave a name for my template.  Now I shift to paste mode, went to another area and just left click, get a blue box showing my starting location, and I hit copy in all diff directions and hold rclick and release and nothing happens.  I have a somewhat charged cap in the wand and no link crystals.  can't rem now if I need a link crystal to do something like this.

**Comment by maruohon** [comment]
Did you get the "Area saved to template" message in chat in Copy mode? You need to hold right click on air for a couple of seconds and release, and then you get the message, only then is the area actually copied. And then when you go into Paste mode and left click to set the primary/red position, you should then get the actual sized bounding box for the entire area, like seen in here: https://www.youtube.com/watch?v=5m281lOQ0IQ
And then, in Paste mode, you can rotate the area by looking in a direction and hitting the toggle key. And when you hold right click on air for a couple of seconds and release, then it will paste the area.

**Comment by DoomSquirter** [comment]
ok now waitasecondhere.  lol sorry to waste ur time like this but...
I do get ghost blocks
not actual blocks that will be placed but the outline of them.  
yes, I missed a step.  I forgot to hit rclick when I copied the blocks  in copy mode.  now that I've done that, if I go into paste mode and set my starter block and rotate view, the ghost  blocks rotate along with the directionals.  so yeah, everything's working perfect so feel free to admit that reality isn't real but pls don't stop this mod because of it lol

**Comment by maruohon** [comment]
Well by ghost blocks I meant (and I thought you also meant) the actual "ghost versions of the actual blocks". So for example in the "Extend continuous" or the Plane mode etc, if you there toggle on the Ghost blocks option, then you will see a slightly translucent version of the actual blocks that would get placed. Where as the template based modes like the Copy/Paste modes, they only currently use the simple wire frame outlines/bounding boxes for the areas and the two corners. So I just don't call those bounding boxes "ghost blocks" in my terminology.

**Comment by DoomSquirter** [comment]
Well I will close this since my interpretation of ghost blocks was working, just user error.  :)  Thanks again man.  great mod, as always.

**Comment by maruohon** [comment]
No problem. I'm glad at least some people like the mod, so that my thousands of hours poured into working on it and learning modding wasn't entirely for nothing... :D

**Comment by DoomSquirter** [comment]
please don't sell yourself short :)  I've said this before and I truly mean it.  This is my favorite mod of 1.10 and would be a top 5 contender if I had used it in 1.7.10 the way it is now (had used mod but just the huge tanks and lasso to put pigs on bats).  I evangelize the mod wherever I go, so hopefully it gets out there more.
