### ISSUE TITLE
Crash when using drawbridges

### ISSUE THREAD

**Issue by modmuss50** [maruohon/enderutilities#42]
This happened on the 1.11.2 beta that is being used on the FTB build server.

https://gist.github.com/modmuss50/d93a522587c0bf7906260baced411c67

Only happened once we started using drawbridges.

**Comment by DinnerBeef** [comment]
it was the normal when i had a stack of stone in their and it made to look like stone

**Comment by maruohon** [comment]
Fixed build here: http://masa.dy.fi/tmp/minecraft/enderutilities/enderutilities-1.11.2-0.7.0-beta.7.jar

**Comment by modmuss50** [comment]
Thanks a lot 👍
