### ISSUE TITLE
Items cannot be taken back out of an ender furnace's input slot

### ISSUE THREAD

**Issue by BrisingrAerowing** [maruohon/enderutilities#44]
I accidentally put an item I didn't want to smelt into the input slot of an ender furnace, and quickly found that I could not take it back out. Is that intended or a bug? I would say bug as the vanilla furnace (and all other modded furnaces I have used) allow things to be taken back out.

**Comment by maruohon** [comment]
Oh really? It may have broken due to some other Container/Slot related changes at some point... Which MC version and mod version is this in?

**Comment by BrisingrAerowing** [comment]
MC 1.10.2
EU: 0.7.2
