### ISSUE TITLE
About .lang

### ISSUE THREAD

**Issue by forestbat** [maruohon/enderutilities#46]
I‘m a translator of Chinese and I want to translate your mod，but I saw your language files can't match the tips in game very well，so I hope you can solve the problem。

**Comment by maruohon** [comment]
Could you elaborate what exactly you mean, and what I should do to improve things? I know a few things are split into parts according to how they are presented in english, and those should rather use a single entry and format specifiers for numbers etc... But are there some other issues as well?

**Comment by forestbat** [comment]
At start I think there are problems with en-us，please don't close the issue before I re-translate the zh-cn。
