### ISSUE TITLE
crashes occuring with newer forge builds upon launch(1.12)

### ISSUE THREAD

**Issue by SDUBZ** [maruohon/enderutilities#47]
Forge: 1.12-2368
Ender utils: 1.12-0.7.0

crash report:
[crash-2017-06-26_17.06.15-client.txt](https://github.com/maruohon/enderutilities/files/1101255/crash-2017-06-26_17.06.15-client.txt)

**Comment by maruohon** [comment]
Fixed on version 0.7.1
