### ISSUE TITLE
Crash with handy bag

### ISSUE THREAD

**Issue by BrisingrAerowing** [maruohon/enderutilities#49]
I clicked on a memory card page button in my large handy bag while holding a 1K storage disk from RS, and the following crash happened:

[Crash Log](https://gist.github.com/BrisingrAerowing/6354120ad91b3781eb34d6e0fcde7477)

**Comment by maruohon** [comment]
It seems to be crashing via the NoMoreRecipeConflict mod's button code. Are you sure you clicked on the Handy Bag button, and not on the recipe cycle button? I've seen those getting placed almost on top of the fourth memory card button.

Could you try (in a test world maybe) first clicking on the Handy Bag buttons with the same item (1K storage disk, and put some items on the storage disk if it had them on the world you were playing, just in case the NBT data of the disk is related), and then on the NoMoreRecipeConflict recipe cycle button, to see if it's actually that one that is crashing?

**Comment by BrisingrAerowing** [comment]
I just tried that, and it was the NMRC button crashing. I'll report this to them.
