### ISSUE TITLE
FATAL error when disconnecting client from smp

### ISSUE THREAD

**Issue by kreezxil** [maruohon/enderutilities#5]
http://paste.ee/p/nOFLe

not a show stopper.

**Comment by maruohon** [comment]
Did you post the correct log? I don't see any fatal errors in that log, at least not for Ender Utilities...

**Comment by kreezxil** [comment]
It doesn't come right out and indicate your mod. In fact there is no crash
report, because the client hung and had to be killed.

I discovered that Forge b1328 and b1329 causes certain mods to throw FATAL
errors when the client connects to a dedicated server. In this case for
you, it threw that on exit and not connect, which is mostly a good thing.

I've got 86 mods in my pack and I'm painfully loading them one at a time
and connecting to my server which is bearing the same configuration as the
client each time. So that error, while not typical, was thrown by your mod.

If I get more information, I'll send it your way.

I'm send reports the Forge team too. As it's odd that a lot of mods would
fail between b1327 and b1328 & b1329. Maybe they can fix something on their
end too; ie, I'm hoping they are at fault.

**Comment by maruohon** [comment]
Hmm I don't know then... I just tried Forge 1329 on my test server, I see no errors on the server nor the client when disconnecting. The other mods I have on the test server are CCC, NEI, InventoryTweaks and TellMe.

**Comment by kreezxil** [comment]
ok, disregard it for now.

**Comment by maruohon** [comment]
Alright, I'll close this for now then.
