### ISSUE TITLE
Crash When Enderman teleport into the Ender Tether

### ISSUE THREAD

**Issue by Zeldri** [maruohon/enderutilities#50]
My server and my client crash when a enderman teleport into the Ender Tether, it crash instantaneously when it's my server and after a minute on client side.

Version of Ender Utilities : 1.10.2-0.7.2
Forge Version : forge-1.10.2-12.18.3.2297-universal

There is the crash log
[Pastebin](https://pastebin.com/91Z3tkaV)

**Comment by maruohon** [comment]
The Ender Tether is not from Ender Utilities.
According to the log: `at net.darkhax.darkutils.features.endertether.TileEntityEnderTether.isEntityCloseEnough(TileEntityEnderTether.java:24)` it is from Dark Utilities.

**Comment by Zeldri** [comment]
My Bad :O sorry with all the mods ender ... I'm confused xD

**Comment by maruohon** [comment]
Hehe, no problem :)

Also, this crash seemed to already have been reported to Dark Utilities.
