### ISSUE TITLE
[1.12] Inserter on chest appeared to cause a crash.

### ISSUE THREAD

**Issue by elucent** [maruohon/enderutilities#51]
Crash report: https://gist.github.com/elucent/3ffea46dfa3729874e6a84107c7b610d

This crash was caused by shift-right-clicking a non-filtered inserter onto one face of a vanilla chest. I was in a Lost Cities dimension in case that's relevant, but I suspect no.

**Comment by maruohon** [comment]
Oh yay, a CME... Everyone loves those! >_>

**Comment by elucent** [comment]
https://www.youtube.com/watch?v=hHP4JtsBnUQ

**Comment by maruohon** [comment]
Perfect! :D

**Comment by BrisingrAerowing** [comment]
CMEs are probably the most insanity inducing thing to ever exist.
