### ISSUE TITLE
Mob Harness server hang

### ISSUE THREAD

**Issue by devryb** [maruohon/enderutilities#6]
The mob harness seems to be hanging the server randomly.
This is a visualvm sample from when it was hung

http://puu.sh/hwTnK/333905d964.png

Version 0.4.0 beta 1

**Comment by maruohon** [comment]
Can you give me more information about this?
Which mob causes this? Is it a single mob, or is it stacked with other mobs?
Does it happen with multiple different mobs or just a specific single one? I'm assuming this is in 1.7.10?
I take it this happens on single player as you have the jvisualvm screenshot?

The only way this  should happen is if the mob is somehow mounted with itself (aka. the Entity.ridingEntity reference points to the entity itself).

I can fix this by breaking out of the loop if the reference points to the entity itself, but more curious as to why this would be happening. I have never encountered it myself, and this should normally NEVER happen. I'm also kind of curious if such mobs are successfully saved to the world data and read back? Afaik this should also lead to an infinite loop on the entity writeToNBT() method.

**Comment by devryb** [comment]
Thanks for the reply!
This was on a server with about 30-40 others on at that time so finding the who/what/how was impossible as when I ask about who did it they just think they're in trouble and don't speak up haha...
So I'm not really sure what more information I can give, I was lucky enough to catch this and grab that report before the server timed out completely and restarted itself.
Yes this is in 1.7.10

**Comment by maruohon** [comment]
Alright. Well, I'm not sure if it makes any sense for me to "fix" this. Like I said, this shouldn't be happening, and the fact that it did means that something caused an entity to have a derped up mount/ridden entity reference (I hope it wasn't the mob harness itself >_>). I can fix this, but I'm pretty sure such an entity will cause issues in other parts of the code as well, like the vanilla entity saving code I mentioned...

Did this happen more than once? You said "randomly", I'm not sure if that implies that it hung more than once? And were there any problems with the world/save when this happened?

**Comment by devryb** [comment]
It happens a second time too not long after, once I blocked players from using that item it stopped.
I'll try to get more information and likely unblock it tomorrow but we can probably close this for now until I can add something to it.
