### ISSUE TITLE
Crafting the Barrel Label crashes my game

### ISSUE THREAD

**Issue by mahilo3550** [maruohon/enderutilities#60]
Minecraft 1.12, Ender Utilities 0.7.5. As soon as the crafting table is filled with the recipe (dark green ingot with 8 sticks around it), the game crashes.

**Comment by maruohon** [comment]
Works fine for me. Please post the crash log so that I could have any idea what is going wrong, and also the Forge version you are using.

**Comment by maruohon** [comment]
Any update on this? If not, then I'll close this because I can't reproduce it.

**Comment by maruohon** [comment]
I'm closing this due to no response and not being able to reproduce on my end.
