### ISSUE TITLE
Barrel Camouflage

### ISSUE THREAD

**Issue by Thiana** [maruohon/enderutilities#62]
Would it be possible to extend the camo functionality to Barrels? Standard or as an upgrade.

Thanks.

**Comment by maruohon** [comment]
How should this work in your opinion? The current camo implementation takes the entire target block's model and uses that. Meaning that a camouflaged barrel would be for example just a full normal cube of stone. If it would need to be a custom barrel model with just the target model's textures, then it would require a more complex model.

Although I guess if I were to take the camo block model, and then add "overlay quads" with the white front item background texture for any front faces, that should work. Or would you prefer it being for example just a stone block with the item rendered on top of the stone? Although if I were to add the overlay model, then it would be easy to change the front background texture to fully transparent or anything else you might prefer in a resource pack, ie. that would be the most flexible solution to this simple model case.

**Comment by Thiana** [comment]
Since white labels are neutral and would work on almost all blocks, I'd vote for the camo + label overlays.

**Comment by Thiana** [comment]
Thanks :)
