### ISSUE TITLE
Kicked from server with Hand Bag auto pickup on

### ISSUE THREAD

**Issue by pip69** [maruohon/enderutilities#65]
I keept getting kicked when I break blocks
"Connection Lost
Internal server error"

Determined it was the Handy Bag by process of elimination.
my exact set-up
Hand Bag (large) using size 12 card far right slot; 
Autopickup (matching) will kick you from the server when you pick up matching items.

I have not tried other possible autopickups

**Comment by maruohon** [comment]
Which version of Minecraft, Forge and the mod are you using? If you are on 1.12.2 and a recent Forge version (2557+), then this would be the same issue as #64.

I have fixed this in my development version, and I'll try to release a new version soon (hopefully today) with that fix included.

(From your description, is sounds like you are playing on a server, so you'll have to wait for the pack to update and the server to include the fixed version. In the mean time the only workaround is to disable the item pickup feature (or just not use it) of the Handy Bag, the Item Pickup Manager and the Nullifier. Or alternatively if it would be possible for the server to use a Forge version before 2557, but I doubt that's possible, as many mods might depend on new functionality added after that version.)

**Comment by pip69** [comment]
You got it about right.  Already disabled the pick-up.  Took a few days to figure out that was the cause.

**Comment by SDUBZ** [comment]
good to hear this is reported already and hope release will be done asap thanks @maruohon for such a great mod :)

**Comment by maruohon** [comment]
The fix has now been released in version 1.12.2-0.7.7. Sorry for the delay... I was trying to implement one more small thing for that release, but was having difficulties getting started on it... so I now released it without that thing just to get the fix out.
