### ISSUE TITLE
[Suggestion] Handy Bag improvements

### ISSUE THREAD

**Issue by jesmores** [maruohon/enderutilities#66]
I just discovered the Handy Bag and this might just be my new favorite backpack item in modded minecraft now!

I hope it's ok to post suggestions here, so here goes:
- There's no documentation on the handy bag, so I'm not quite sure what some of the buttons do, e.g. "block quick actions" and "update items"
- I have one memory card for all my tools that I switch between, and then separate memory cards for block drops and mob drops. Given that use case, I was hoping that the "restock" and "pickup" mode buttons could be set on a per-memory card basis instead of for the whole bag, so I could set the mob drop and block drop to auto-pickup, but not the tools card.
- Related to the previous point, if the bag is in pickup (matching) mode, it will only pickup items that match the contents of the currently selected memory card, and not the others. So if I were running around killing mobs, but I had my tools memory card selected, it wasn't picking up the mob drops.

I'm using EnderUtilities-1,12,2-0.7.7

**Comment by jesmores** [comment]
Ah I figured it was perf related since the whole "current card only" behavior was also happening to handy chests and their double click quick action feature. I hope you get a breakthrough as you're doing the inventory refactor :)

Actually, speaking of the Handy Chest, do they not look inside the Handy Bag to pull items when you double click them? I was doing some tests last night and it seems to only work from the player's inventory. I was hoping to quick-dump my mob and block drops cards from the bag, but even with the appropriate cards selected on both the bag and the chest, it wasn't happening.

**Comment by maruohon** [comment]
The Chests do not pull from the Bag no. However the Handy Bag does have auto-dumping and pickup functionality on its side. Basically you have to set the bag into restock mode and sneak + right click with the bag on an inventory to dump stuff from the bag to that inventory, or to suck in stuff from the inventory you have to set it to pickup mode and then sneak + right click the inventory with the bag. This should work with any blocks with inventories (which have the Forge `IItemHandler` capability).

**Comment by jesmores** [comment]
I guess I was expecting them to work with each other since they both had "Handy" in their name :) - in any case, thanks for the help!

**Comment by maruohon** [comment]
Well they *should* work together, but you just need to sneak + right click with the bag instead of the double click... Not sure if I want to add that either, as it might lead to a lot of cases where the player does not want to dump the bag contents but only their own inventory... hmm :thinking:

**Comment by maruohon** [comment]
Two of the issues were resolved in version 0.7.9, and the third, "use all cards at once" isn't really feasible, nor something I would want the bag to do personally.
