### ISSUE TITLE
Check for End Biome not dim #

### ISSUE THREAD

**Issue by orbwoi** [maruohon/enderutilities#67]
Hello,

I'm working on a modpack and have come across an issue. I have the more than one copy of the end (e.g. not always dim 1) and would like the mod to still work correctly.

Looking at the code, you have hard-coded the dimension id 1 for many checks. Could could instead check for the end biome or else provide a whitelist of dimension in the config?

**Comment by maruohon** [comment]
A dev build to test with is available here: https://pena2.dy.fi/tmp/minecraft/mods/enderutilities/enderutilities-1.12.2-0.7.9-dev.20180326.155454.jar

What is your timeline for the pack? Not sure if I want to push a new version just for this just yet if it's not quite yet necessary. I have some bigger refactoring planned, but no idea yet when I'll have time to do all that... But if/when your pack is about to release I can upload this to CF then.
