### ISSUE TITLE
DisableRecipes config is non functional

### ISSUE THREAD

**Issue by SlyCedix** [maruohon/enderutilities#74]
Disable recipes section of my config
`DisableRecipes {
    B:disableRecipeAdjustableStorageUnit=false
    B:disableRecipeAdvancedQuickStacker=false
    B:disableRecipeBarrel=false
    B:disableRecipeBuildersWand=false
    B:disableRecipeCreationStation=true
    B:disableRecipeDrawbridge=false
    B:disableRecipeEnderArrow=false
    B:disableRecipeEnderAxe=false
    B:disableRecipeEnderBag=false
    B:disableRecipeEnderBow=false
    B:disableRecipeEnderBucket=false
    B:disableRecipeEnderElevator=false
    B:disableRecipeEnderFurnace=false
    B:disableRecipeEnderHoe=false
    B:disableRecipeEnderInfuser=false
    B:disableRecipeEnderLasso=false
    B:disableRecipeEnderPearl=false
    B:disableRecipeEnderPearlElite=false
    B:disableRecipeEnderPickaxe=false
    B:disableRecipeEnderPorterAdvanced=false
    B:disableRecipeEnderPorterBasic=false
    B:disableRecipeEnderShovel=false
    B:disableRecipeEnderSword=false
    B:disableRecipeEnergyBridgeReceiver=false
    B:disableRecipeEnergyBridgeResonator=false
    B:disableRecipeEnergyBridgeTransmitter=false
    B:disableRecipeFloor=false
    B:disableRecipeFrame=false
    B:disableRecipeHandyBag=true
    B:disableRecipeHandyChest0=true
    B:disableRecipeHandyChest1=true
    B:disableRecipeHandyChest2=true
    B:disableRecipeHandyChest3=true
    B:disableRecipeIceMelter=false
    B:disableRecipeIceMelterSuper=false
    B:disableRecipeInserter=false
    B:disableRecipeInventorySwapper=false
    B:disableRecipeJunkStorageUnit=false
    B:disableRecipeLivingManipulator=false
    B:disableRecipeMassiveStorageBundle=false
    B:disableRecipeMassiveStorageUnit=false
    B:disableRecipeMemoryChest0=false
    B:disableRecipeMemoryChest1=false
    B:disableRecipeMemoryChest2=false
    B:disableRecipeMobHarness=false
    B:disableRecipeModuleEnderCapacitor0=false
    B:disableRecipeModuleEnderCapacitor1=false
    B:disableRecipeModuleEnderCapacitor2=false
    B:disableRecipeModuleLinkCrystalBlock=false
    B:disableRecipeModuleLinkCrystalLocation=false
    B:disableRecipeModuleLinkCrystalPortal=false
    B:disableRecipeMolecularExciter=false
    B:disableRecipeNullifier=false
    B:disableRecipePartBarrelCapacity=false
    B:disableRecipePartBarrelLabel=false
    B:disableRecipePartBarrelStructure=false
    B:disableRecipePartEnderAlloy0=false
    B:disableRecipePartEnderAlloy1=false
    B:disableRecipePartEnderAlloy2=false
    B:disableRecipePartEnderCore0=false
    B:disableRecipePartEnderCore1=false
    B:disableRecipePartEnderCore2=false
    B:disableRecipePartEnderRelic=false
    B:disableRecipePartEnderRope=false
    B:disableRecipePartEnderStick=false
    B:disableRecipePartMemoryCardItems10b=true
    B:disableRecipePartMemoryCardItems12b=true
    B:disableRecipePartMemoryCardItems6b=true
    B:disableRecipePartMemoryCardItems8b=true
    B:disableRecipePartMemoryCardMisc=false
    B:disableRecipePartMobPersistence=false
    B:disableRecipePhasingBlock=false
    B:disableRecipePickupManager=false
    B:disableRecipePortalPanel=false
    B:disableRecipePortalScaler=false
    B:disableRecipeQuickStacker=false
    B:disableRecipeRuler=false
    B:disableRecipeSoundBlock=false
    B:disableRecipeSyringeEmpty=false
    B:disableRecipeSyringeParalyzer=false
    B:disableRecipeSyringePassifier=false
    B:disableRecipeSyringeStimulant=false
    B:disableRecipeToolWorkstation=false
    B:disableRecipeVoidPickaxe=false
}`

![image](https://i.imgur.com/jC91IPi.png)

![image](https://i.imgur.com/OS0uzUX.png)

![image](https://i.imgur.com/bNoNI3N.png)

As you can see, the recipes are still present despite being disabled in the config.

I also tried removing the recipes with crafttweaker, which had some success as I could remove the item recipes, but the creation station recipe could not be removed.

**Comment by maruohon** [comment]
Yeah those configs aren't functional anymore since the addition of the json recipe system in 1.12. I don't know why I forgot to remove the configs... I'll do that for the next version I guess. The only recipe config that works atm is the Ender Elevator one, because that one still uses a code-based custom recipe. But even that should probably be changed into a json recipe with a factory.

CraftTweaker should be used for disabling recipes since 1.12. I don't know why the Creation Station would be any different than anything else... Are you sure you didn't make a typo in the CT script?

**Comment by SlyCedix** [comment]
I may have had a typo, just readded the script and the recipe seems to be removed.
