### ISSUE TITLE
Paired Portals?

### ISSUE THREAD

**Issue by Thiana** [maruohon/enderutilities#78]
How do you set the destination for a paired portal crystal? I've tried [Shift-,][Left,Right]Clicking on both the frame and the keypad but the crystal never marks itself as linked? Thanks.

Versions:
forge-14.23.4.2739
enderutilities-1.12.2-0.7.11

**Comment by maruohon** [comment]
It's sneak + right click on a portal block, as it will teleport you to the linked position, assuming there is still a portal block there when the teleport attempt happens.

**Comment by Thiana** [comment]
Ah, in that case this is now a bug report. Shift is my sneak key.

I've confirmed the problem with just forge and EnU loaded.

To replicate: 
Create a small portal.
Sneak right-click portal crystal on center block of portal.
Check crystal (it remains unlinked).

![2018-07-29_12 39 34](https://user-images.githubusercontent.com/405832/43368561-20092a70-932d-11e8-88fa-ff748f84b113.png)

**Comment by maruohon** [comment]
Okay to clarify, a Portal block means the actual portal blocks that are created when you activate the portal, ie. not the Portal Frame block.

**Comment by Thiana** [comment]
Ah ok, that works. To me the Portal (a structure) is made from portal frame blocks, which leads to some confusion. Might I suggest a slight wording change to ```Sneak right-click on the center of an active Portal to bind```
