### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by GustoniaEagle** [maruohon/enderutilities#8]
Using Ender Utilities 0.4.0. Crash occurs during launch.
Since the crash report doesn't actually mention Ender Utilities, I was able to locate the cause by disabling mods individually, and it turned out that everything worked when Ender Utilities was disabled.
For the record, version 0.3.5.1 works fine whilst 0.4.0 does not.

http://pastebin.com/bykyDfsT

**Comment by maruohon** [comment]
Ugh. Does Ender Utilities work on its own for you? Have you changed any configs (disabled items etc.) of it? I have never seen a crash related to texture loading, or that is what it seems like O_o

**Comment by GustoniaEagle** [comment]
Ender Utilities on it's own works fine, I haven't changed any configs for Ender Utilities and no, neither have I. When I get the chance I'll try removing mods one by one to find the cause.

**Comment by GustoniaEagle** [comment]
Huh. Just added it back to the pack, and it is working now! No idea what caused it.

**Comment by maruohon** [comment]
Huh, well that is strange.
