### ISSUE TITLE
Nutrition mod & Ender Utilities Slight problem

### ISSUE THREAD

**Issue by SirTwsted** [maruohon/enderutilities#85]
When using Handy Bag from Ender Utilities,
The nutrition button does not appear when pressing [E].
Would love to see the button so I can get into the nutritions panel to view my nutrition.
I will also post this on the Nutrition GitHub so they will also know,
https://github.com/WesCook/Nutrition/issues/147
so both you guys can know of the small problem.
thanks.

**Comment by maruohon** [comment]
Yeah the bag GUI won't have any of the extra stuff that mods may add to the vanilla player inventory GUI. You can simply sneak when you open your inventory to not open the bag, that way you can have access to the stuff that gets added to the normal player inventory GUI.

I don't know if there even is any feasible way for me to try to make an arbitrary number of mod-added buttons work in my GUI, and at least I'm not looking forward to trying to figure that out. By which I mean that I probably won't even try to look into it. It's a minor annoyance to hold sneak while opening the inventory, versus quite likely a huge amount of time and effort to try to fix that, and it might not even be possible, and would probably need special support for each and every mod that ads some buttons (?).

**Comment by SirTwsted** [comment]
ahh ok.
Thank you for taking the time out and replying.  I appreciate it.
thanks. :D
