### ISSUE TITLE
Handy-Chest - Mekansim Logistical Transporter stop transferring items before the output storage is really full

### ISSUE THREAD

**Issue by Fireztonez** [maruohon/enderutilities#88]
Hello,
I have report this issue to Mekanism, and the dev think this issue have to be fix on your side.

**So, what append exactly;**
The Logistical Transporter stop transfering items when the contener (Ender Utilites Handy Chest Extended) contain about 5120 of that item (1 stack 1/4 on the chest...). If I remove 1 stack, the logistical transporter will immediately take and send 1 more stack, bot still stop at the same amount...

![logistical-transpoter_stop-5120](https://user-images.githubusercontent.com/19277301/56452635-23e77800-6301-11e9-9397-efb9625d28f7.png)

Here the link of the Mekanism issue: https://github.com/mekanism/Mekanism/issues/5414

**Comment by Fireztonez** [comment]
@maruohon Do you have a new Dev version for me to test? Because for now, the issue still happen with the version 9.7.2.373 of Mekanism.

If you have a dev version I will be really happy to test for you, if that fix the issue!

**Comment by maruohon** [comment]
Here is a dev build: https://masa.dy.fi/tmp/minecraft/mods/enderutilities/enderutilities-1.12.2-0.7.13-dev.20190421.214003.jar

Note that the Creation Station JEI recipe transfer doesn't work at all in this build... I need to rewrite the fix I did for that, because it used stuff not in the JEI API, and thus it couldn't be built against the API alone...

**Comment by Fireztonez** [comment]
Ok thank's for the information and for the dev version!

**Comment by Fireztonez** [comment]
Perfect, the Handy Chest issue with Mekanism is now fixed!!

For the Creation Station it's act a little weird wen you do craft, sometime the output is not show and if is show, when you Shift-Click the output to ask to craft a stack it take about 5 second before the items gets really in your inventory, sometime items appear in your hand or some-times it just craft and place in the internal storage, but the dealy is really big. I think that thing need somes love question to make a little code rewrite... 

I don't really know how if this is caused by the fact you didn't use vanilla IInventory and methode or not. But the JEI issue look like is not the only issue. The only thing I know, this is the first time I saw a crafting table lagging Like that.

**Comment by maruohon** [comment]
Yeah the crafting lag is due to the vanilla crafting system being just one massive list, and in modded the number of recipes is quite massive, so checking for a recipe match is rather slow. That's what the FastWorkBench mod (was it called that?) does/fixes, but I think it only does it for the vanilla crafting table. So I need to add some form of recipe caching to my crafting GUIs as well.

**Comment by Fireztonez** [comment]
Yeah, FastWorkbench mod replace the Vanilla Crafting table, but loot like it do things for somes modded crafting table too (But this is possibly hard-coded, question to replace somes arguments). I remove and test without FastWorkbench and with the Tinker crafting table (How I use every-time, all craft is just instant), but a Vanilla Crafting Table take about 1 or 2 second to craft a stack... So yeah, I think you got a point!

But, other thing, probably the fact or using  items from the internal inventory, if the Crafting Table is not really optimized, if it look all the list every time, it try to craft one and look if item is in the internal inventory, this can clearly caused lot more crafting lag I imagine... I'm not totally sure how Crafting table work in vanilla, but for what I heard, I think this is the big issue with the crafts...

So, what I learn today is first, the Crafting Station from Tinker is not supported by Fast Workbench, but Tinker have optimized the Crafting system directly and have done a really good job for that. Cyclic Crafting interface 3x3 and the Actually Addition Crafting is optimized by a FastWorkbench support.

Thank's for that, I learn a lot with all that tests and thge way of dev like you reply to somes issue, and this can only be good to make better modpack :).

And, if it can help you, you can probably take a look of the FastWorkbench code and I think if you need help, you can contact the dev, for what is say in the Mod Description and comments, the dev work a lot with mod dev question to optimised most crafting table with FastWorkbench...
