### ISSUE TITLE
Server crash on load

### ISSUE THREAD

**Issue by brunyman** [maruohon/enderutilities#90]
Server is running on modpack SkyFactory4 version 4.0.5.
Forge: 1.12.2-14.23.5.2831
SpongeForge: 1.12.2-2768-7.1.5
EnderUtilites: 1.12.2-0.7.12

Crash Report:  https://pastebin.com/hqnDGsKB

Log Error:  https://pastebin.com/wEpQYUnx

**Comment by maruohon** [comment]
I'm not able to reproduce the crash on my test server using the same Forge and Sponge versions. I'm not running the SF4 pack though, just Ender Utilities and a couple other of my own mods. But based on the crash log, somehow the fastutil library seems to be missing or incomplete in your case. It's supposed to be included inside the vanilla server jar though, so I have no idea how it could be missing... Maybe try re-downloading the vanilla 1.12.2 server jar from https://mcversions.net/ ?

**Comment by maruohon** [comment]
Closing due to no response or activity
