### ISSUE TITLE
Handybag items get deleted

### ISSUE THREAD

**Issue by EDToaster** [maruohon/enderutilities#95]
Version: enderutilities-1.12.2-0.7.12.jar
Modpack: SkyFactory 4 (4.0.8), Minecraft 1.12.2, forge-14.23.5.2838

Sometimes when sorting the player inventory with the bag in the inventory, the bag gets sorted into the handy bag itself, which then deletes all the items that were in the bag.

I'll try to reproduce it again, but I think this is just a one-off thing.

**Comment by maruohon** [comment]
This is supposed to be impossible to do. Which sorting function do you mean exactly? The player inventory sort button in the bag GUI, or one of the move-items buttons, or something external such as Inventory Tweaks?

**Comment by EDToaster** [comment]
Not sure what caused it. I pressed the "Sort Player Inventory" in the middle of the GUI. Trying to reproduce it now, but I'm having trouble doing so. The bug happened when my inventory was quite full, so that may be an issue? I'll try to see what I can gather from my end.

**Comment by EDToaster** [comment]
# Steps to reproduce

1. Grab 2 or more unstackable items
![2019-08-17_15 18 08](https://user-images.githubusercontent.com/7676229/63217863-69c31a00-c102-11e9-9742-67410e6b17a2.png)

2. Sort those items (They will become stacked, a bug?)
![2019-08-17_15 18 15](https://user-images.githubusercontent.com/7676229/63217864-69c31a00-c102-11e9-9b36-5c598cace687.png)

3. Fill remainder of inventory with any (stackable) item
![2019-08-17_15 18 28](https://user-images.githubusercontent.com/7676229/63217865-69c31a00-c102-11e9-8beb-f40d215e635d.png)

4. Sort again
![2019-08-17_15 18 30](https://user-images.githubusercontent.com/7676229/63217866-69c31a00-c102-11e9-92a6-1d885fe66e5b.png)

5. The stacked unstackable items will become unstacked, which then somehow deletes the handybag.

## Causes

I think there are two bugs here.

1. Unstackable items should not be stacked upon sorting
1. When sorting an inventory results in more itemstacks than there are itemslots, the remaining itemstacks should be thrown into the world, rather than being deleted.

Hope this helps!

**Comment by EDToaster** [comment]
EDIT: This bug also seems to duplicate non-stackable items. In step 3 there are 6 chestplates. However, in step 4, we have 2 extra chest plates. I just restarted my world and confirmed this isn't a client side bug.
