### ISSUE TITLE
Handy Bag too large

### ISSUE THREAD

**Issue by zeeoric** [maruohon/enderutilities#97]
So i put my handy bag into my ME storage, everything was fine, i went to take the handy bag out and i received the following error and was booted from the server

Internal Exception: java.lang.Illegal Argument Exception : Payload May Not Be Bigger Than 32767 Bytes

So doesn't take a genius to figure out i had a lot of things in my bag.... but now all of that is lost to me...simple learning lesson i guess.... but would be nice if there was a way to access the bag and take things out of it when it is in a storage chest or ME storage or the like.... maybe a control right click to access inventory and take some out so that i could use the bag again and not lose everything i spent 3 days on.

**Comment by maruohon** [comment]
I was supposed to rewrite all my storage items in 0.8.0 to use an external storage system and only store the UUID for each inventory in the memory card, thus fixing the issue with very large item NBT tags. But I haven't really worked on EnU actively in like 2 years now...

So is it the ME terminal or whatever that boots you from the server when you try to take out the bag? Or do you get kicked when you just have the bag in your inventory? AFAIK the NBT size limit for the item in your inventory is 2 MB, which has also been crossed by some people by nesting something like RFTools storage disks or whatever in a Handy Bag (a very bad idea in general to deeply nest storage items...). If it just kicks you when you try to take it out manually, maybe you can pump it out of the system into a chest with an export bus?

**Comment by zeeoric** [comment]
it boots me when trying to take it out, i will try the export bus

**Comment by zeeoric** [comment]
export bus wont work because there are items in the handy bag it sees it as a separate entity, but it pulled an empty one out no problem....lol

**Comment by maruohon** [comment]
Isn't there an option for fuzzy match that ignores NBT data?

**Comment by zeeoric** [comment]
fuzzy worked, thank you
