### ISSUE TITLE
Ender Furnace automation possible?

### ISSUE THREAD

**Issue by Keridos** [maruohon/enderutilities#98]
Is it possible to automate the ender furnace (as in taking items out of it (not via the ender chest).

If not, could you make that possible?

**Comment by maruohon** [comment]
It should be possible, but I think you need to pull out items from the bottom. It's similar to how vanilla furnaces work, if I remember right.

**Comment by Keridos** [comment]
No, does not seem to work, input via side works though.

**Comment by maruohon** [comment]
I take it that other mod didn't support capabilities?

**Comment by Keridos** [comment]
Well its a minor thing but your furnaces expose the charcoal slot on bottom, and the simple storage import bus gets stuck on nonimportable items. basically the slot is "read"only and it tries to extract it over and over again.

**Comment by maruohon** [comment]
That's also how it works on the vanilla furnaces though, the fuel slot is exposed so that empty buckets or other container items can be pulled out. Does it not get stuck with vanilla furnaces? Does it use the vanilla inventory interfaces directly and differently in that case then maybe?
